#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Using RP_lib to create a temperature over time graph

Created on Tue Sep 24 20:38:04 2019
@author: mallen
"""
import numpy as np
import matplotlib.pyplot as plt
from RP_lib import Bubble




